#!/usr/bin/env bash

for SUBJECT in 1 2 3 4 7 8 9 10 11 12 13 14 16 17 18 19 20 21 23
do
    printf "Subject $SUBJECT\n"
    for SESSION in 1 2 3 4 5
    do
        printf "Session is $SESSION"
        python xplor_preprocess.py $SUBJECT $SESSION
        printf "Done with subject $SUBJECT and session $SESSION! :) \n\n\n"
        sleep 3
    done
done
